all: ./test.html

# Makefile info:
./test.html: ./test.html.tir ./test_sub.html ./test ./test_sss3.html ./../testicon.png
	tir './test.html.tir' -o './test.html' -bw '<!--[tir:begin]' -ew '[tir:end]-->' -y -cfg ./tir.cfg

